language: python
python:
  - "3.6"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mkdir ssl/
  - mv travis-fullchain.pem.txt ssl/fullchain.pem
  - mv travis-privatekey.pem.txt ssl/privkey.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config