  - alias: 'Misc: Update config if travis build is successfull'
    trigger:
      platform: state
      entity_id: sensor.paulmona_myhomeassistantconfig_last_build_state
      to: 'passed'
    action:
    - service: script.git_pull

  - alias: Daily Backup at 2 AM
    trigger:
      platform: time
      at: '02:00:00'
    action:
      service: hassio.snapshot_full
     
  - alias: Backup to Google Drive Daily
    trigger:
      platform: time
      at: '03:00:00'
    action:
      service: rest_command.do_backup