  - alias: 'Misc: Update config if travis build is successfull'
    trigger:
      platform: state
      entity_id: sensor.paulmona_myhomeassistantconfig_last_build_state
      to: 'passed'
    action:
    - service: script.git_pull  